
- name: Allow all Nebula traffic in the Lighthouse firewall
  community.general.ufw:
    rule: allow
    proto: udp
    port: 4242
    comment: "Allow Nebula in"
  when: am_lighthouse is defined and am_lighthouse

- name: Create the Nebula directory
  ansible.builtin.file:
    path: /opt/nebula
    state: directory

- name: Get the Nebula package from GitHub
  ansible.builtin.get_url:
    url: https://github.com/slackhq/nebula/releases/download/v1.7.2/nebula-linux-amd64.tar.gz
    dest: /opt/nebula

- name: Extract the Nebula package
  ansible.builtin.unarchive:
    src: /opt/nebula/nebula-linux-amd64.tar.gz
    dest: /opt/nebula
    remote_src: true
  
- name: Deploy the Nebula Root certificate
  ansible.builtin.copy:
    src: "{{ op_directory }}/nebula/ca.crt"
    dest: "/opt/nebula/ca.crt"

- name: Deploy the Nebula client certificate
  ansible.builtin.copy:
    src: "{{ op_directory }}/nebula/{{ uuid }}.crt"
    dest: "/opt/nebula/host.crt"

- name: Deploy the Nebula client key
  ansible.builtin.copy:
    src: "{{ op_directory }}/nebula/{{ uuid }}.key"
    dest: "/opt/nebula/host.key"

- name: Deploy the Nebula configuration
  ansible.builtin.template:
    src: '{{ playbook_dir }}/../templates/nebula/nebula-configuration.yaml.j2'
    dest: '/opt/nebula/config.yaml'

- name: Create the Nebula service
  ansible.builtin.template: 
    src: '{{ playbook_dir }}/../templates/nebula/nebula.service.j2'
    dest: /etc/systemd/system/nebula.service

- name: Load, Enable, and Start the Nebula service
  ansible.builtin.service:
    name: nebula
    state: reloaded
    enabled: true

- name: Open the UFW firewall to allow Nebula subnet to communicate freely in (standard)
  community.general.ufw:
    rule: allow
    interface: nebula1
    direction: in
    comment: "Allow in Nebula Network to all"

- name: Open the UFW firewall to allow Nebula subnet to communicate freely out (standard)
  community.general.ufw:
    rule: allow
    interface: nebula1
    direction: out
    comment: "Allow out Nebula Network to all"
    
- name: Open the UFW firewall to allow Nebula subnet to communicate freely (routes)
  community.general.ufw:
    rule: allow
    interface_in: nebula1
    interface_out: nebula1
    route: yes
    comment: "Allow Nebula Network to all"
