- name: Install all Docker dependencies
  apt:
    pkg:
      - ca-certificates
      - gpg
      - gnupg
      - lsb-release
      - curl
      - python3-pip
    state: present
    update_cache: yes

- name: Install Docker pip dependency
  ansible.builtin.pip:
    name: docker

- name: Remove the Docker GPG apt key if present (need to or next step fails)
  ansible.builtin.file:
    path: "/usr/share/keyrings/docker-archive-keyring.gpg"
    state: absent

- name: Add Docker GPG apt Key
  shell: |
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add the Docker official repository for Debian to APT repos
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Install Docker and all Docker Plugins
  ansible.builtin.apt: 
    pkg:
      - docker-ce
      - docker-ce-cli 
      - containerd.io 
      - docker-compose-plugin
    state: latest
    update_cache: yes
