################################ WARNING ################################
# It is NOT recommended to place credentials/keys in this file!
# To protect sensitive material, set your HISTCONTROL env var to
# ensure that the command is not stored in the shell history and
# then use the export command to pass in creds through env vars.
#########################################################################
global:
  project_directory: ./deployments
  terraform_path:
  ansible_path: 
  nebula_path: 
  nebula_subnet: 10.36.0.0/24
  container_registry: 
  container_registry_username: # If using AWS ECR, specify your AWS_SECRET_KEY_ID
  container_registry_password: # If using AWS ECR, specify your AWS_SECRET_ACCESS_KEY
  container_registry_strategy: default # If using AWS ECR, specify "aws"


# ===================== Miscellaneous Configurations =====================
ansible_configuration:
  global:
    main_email: # Email for SSL Cert Generation
  # Default users for all systems
  default_users:
    terry:
      user: terry
      public_ip: 8.8.8.8
      public_key: # Either public key value or path to the public key file
    terry2:
      user: terry2
      public_ip: 8.8.8.8
      public_key: # Either public key value or path to the public key file
  # Remote configurations in Git repositories that can be dynamically loaded into Ansible
  remote:
    - name:
      repo_url:
      username:
      personal_access_token:
      is_package: true
  # Additional playbooks to run with each command provided
  # For these to work THEY MUST LIVE in the ./playbooks/custom directory and then the "path" should be the name of the playbook file
  extended_plays:
    create:
      - path:
        extra_vars:
    add:
      - path:
        extra_vars:
    destroy:
      - path:
        extra_vars:
    reconfigure:
      - path:
        extra_vars:

slack:
  # Slack Webhook to send notifications to upon completion
  webhook_url:

elastic:
  # FQDN or IP address of Elastic Server (must be on internet and accessible) formatted as 'server.elastic.com' or '8.8.8.8'
  elastic_server:
  elastic_api_key: 


# ===================== Cloud Configurations =====================
aws:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION:

azure:
  ARM_CLIENT_CERTIFICATE_PASSWORD:
  ARM_CLIENT_CERTIFICATE_PATH:

digitalocean:
  DIGITALOCEAN_ACCESS_TOKEN: 

godaddy:
  GODADDY_API_KEY:
  GODADDY_API_SECRET:

namecheap:
  NAMECHEAP_USER_NAME:
  NAMECHEAP_API_USER:
  NAMECHEAP_API_KEY:

proxmox:
  PM_API_TOKEN_ID:
  PM_API_TOKEN_SECRET:
  PM_API_URL:
  PM_TARGET_NODE:
  PM_OS_TEMPLATE:
  PM_STORAGE_TARGET:

# ===================== C2 Configurations =====================
cobaltstrike:
  COBALTSTRIKE_PASSWORD:
  # If left blank, a dummy profile will be deployed
  COBALTSTRIKE_MALLEABLE_C2:
